
version: "3"
services:
  server:
    build: server/
    restart: on-failure
    ports:
      - 5000:5000
    networks:
      - app-network
  client:
    build: client/
    restart: on-failure
    depends_on:
      - server
    ports:
      - 3000:3000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
